package com.example.sd_28_phostep_be.service.account.Client.impl.KhachHang;

import com.example.sd_28_phostep_be.dto.account.request.KhachHang.KhachHangQuickCreateRequest;
import com.example.sd_28_phostep_be.dto.account.response.KhachHang.KhachHangDTOResponse;
import com.example.sd_28_phostep_be.modal.account.KhachHang;
import com.example.sd_28_phostep_be.modal.account.TaiKhoan;
import com.example.sd_28_phostep_be.repository.account.KhachHang.KhachHangRepository;
import com.example.sd_28_phostep_be.repository.account.TaiKhoanRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.List;

@Service
public class KhachHangServices {
    private final KhachHangRepository khachHangRepository;
    private final TaiKhoanRepository taiKhoanRepository;

    public KhachHangServices(KhachHangRepository khachHangRepository, TaiKhoanRepository taiKhoanRepository) {
        this.khachHangRepository = khachHangRepository;
        this.taiKhoanRepository = taiKhoanRepository;
    }

    public List<KhachHang> getall() {
        return khachHangRepository.findAllExceptKH001();
    }

    /**
     * Get active customers for sales counter with phone numbers from account table
     */
    public Page<KhachHangDTOResponse> getActiveCustomersForSales(Pageable pageable, String keyword) {
        return khachHangRepository.findActiveCustomersForSales(pageable, keyword);
    }

    /**
     * Quick create customer with only name and phone number for sales counter
     */
    public KhachHang quickCreateCustomer(KhachHangQuickCreateRequest request) {
        // Create TaiKhoan first
        TaiKhoan taiKhoan = new TaiKhoan();
        taiKhoan.setSoDienThoai(request.getSoDienThoai());
        taiKhoan.setMatKhau("123456"); // Default password
        taiKhoan.setDeleted(true);
        taiKhoan = taiKhoanRepository.save(taiKhoan);
        
        // Create KhachHang - ma will be auto-generated by database
        KhachHang khachHang = new KhachHang();
        khachHang.setTen(request.getTen());
        khachHang.setCreatedAt(Instant.now());
        khachHang.setDeleted(true);
        khachHang.setTaiKhoan(taiKhoan);
        
        khachHang = khachHangRepository.save(khachHang);
        
        // Update TaiKhoan username with the auto-generated customer code
        taiKhoan.setTenDangNhap(khachHang.getMa());
        taiKhoanRepository.save(taiKhoan);
        
        return khachHang;
    }
}
